### ISSUE TITLE
Discovery service 'lite' plan doesn't deploy

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-online-store#103]
The old name for the free tier of discovery was 'free', but it looks like it changed to "Lite".
Neither 'free' nor 'Lite' nor 'lite' seem to work with "deploy to Bluemix"
![image](https://user-images.githubusercontent.com/14651388/28989430-7ddd0a10-7932-11e7-8d92-c7e114801412.png)

Doing 'cf services' shows the name 'lite':
[scott@oc0486027055 watson-online-store]$ cf services
Getting services in org scott.dangelo / space sandbox as scott.dangelo@ibm.com...
OK

name                      service           plan       bound apps   last operation
cloudantNoSQLDB-service   cloudantNoSQLDB   Lite                    create succeeded
Conversation-sandbox      conversation      free                    create succeeded
Discovery-scott           discovery         lite                    create succeeded

While testing this on a fork, I accidentally merged the change to 'lite' into this repo. I'll leave as is until we figure this out.
Meanwhile, Mitchell Mason is aware of this in wdc-community.slack.com and is escalating.

**Comment by markstur** [comment]
Was fixed with lowercase 'lite' in https://github.com/IBM/watson-online-store/pull/102 (commit e363953f13e6071d2777914bc8da74d3dd9162f0) plus commit 2ba72ab99c74b602929ec22cb30c6e7895d13752
