### ISSUE TITLE
AttributeError: 'DiscoveryV1' object has no attribute 'get_environments'

### ISSUE THREAD

**Issue by deveops** [IBM/watson-online-store#119]
I get this error when running the app in bluemix. It then crashes.
It looks like watson_developer_cloud.DiscoveryV1 has changed its API.

**Comment by stevemar** [comment]
thanks @deveops we'll take a look at this

**Comment by markstur** [comment]
reproduced

**Comment by markstur** [comment]
Closed with #120

**Comment by Ayshine** [comment]
AttributeError: 'DiscoveryV1' object has no attribute 'get_environments'
I have the same error.

**Comment by utgarda** [comment]
Looking at #120 shows that now we need to use `list_environments` instead.
