### ISSUE TITLE
remove the deprecated deployment tracker

### ISSUE THREAD

**Issue by markstur** [IBM/watson-online-store#124]
One of the trackers is discontinued.  Update README too.

12/5/2017 5:44:49 PM	OUT	undefined	Uploaded stats: {"ok":false,"error":"This service is discontinued. Refer to https://github.com/IBM-Bluemix/cf-deployment-tracker-service/wiki/Deployment-Tracker-Service-status for more information."}

**Comment by ptitzler** [comment]
Yes, please remove the dependency  on the old tracking library and code. Refer to the following document for details and migration instructions https://github.com/IBM-Bluemix/cf-deployment-tracker-client-python/wiki/migrating-to-the-new-metrics-tracker-client.

**Comment by scottdangelo** [comment]
The cf-deployment tracker is removed.
