### ISSUE TITLE
slack connection fails while running the script locally

### ISSUE THREAD

**Issue by anlinjv** [IBM/watson-online-store#128]
Founds the bot id correctly. But the rtm_connect statment returns false and can't connect to slack. 
![image](https://user-images.githubusercontent.com/26163411/35566398-43bbc2ee-05e7-11e8-9c9c-a31d939a1fdb.png)

**Comment by scottdangelo** [comment]
We have just fixed an issue that was causing failure.
I am now able to run the application locally without failure.
I'll close this. Please re-open if you still have an issue.

**Comment by xkluan** [comment]
Hello, how did you do to solve this problem? I have the same problem now...
