### ISSUE TITLE
Python 3.6.4 (Anaconda) interprets strings as bytes

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-online-store#142]
Dues to [changes](https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal) between python 2.x and 3.x, the strings for our online store items are now interpreted as bytes:
```
Your cart is:
1) b'Performance Cap: http://www.logostore-globalid.us/ProductDetail.aspx?pid=211897\n'
2) b'THINK Cap: http://www.logostore-globalid.us/ProductDetail.aspx?pid=131626\n'
3) b'THINK Mug: http://www.logostore-globalid.us/ProductDetail.aspx?pid=132254\n'
```

**Comment by stevemar** [comment]
if it's just affecting printing to console we probably just want to wrap the output in a `str()` before it's called. https://github.com/IBM/watson-online-store/blob/master/watsononlinestore/watson_online_store.py#L731-L733

**Comment by scottdangelo** [comment]
Yes, the solution is to convert the bytes array to a string.
Unfortunately, I haven't been able to find the proper place to do that, after looking in several locations.
It is not in L#731-733

**Comment by sanjeevghimire** [comment]
L#731 uses `item.encode(...)` which creates a byte string hence show `b'....' `. Removed the encode to treat it as the string.

**Comment by stevemar** [comment]
reopening so the PR can close it.
