### ISSUE TITLE
DiscoveryV1' object has no attribute 'test_document

### ISSUE THREAD

**Issue by folajimia** [IBM/watson-online-store#143]
I get this when use the attribute  discovery.test_document

as stated in the discovery documentation

import sys
import os
import json
from watson_developer_cloud import DiscoveryV1

discovery = DiscoveryV1(
  username="{username}",
  password="{password}",
  version="2017-11-07"
)

with open(os.path.join(os.getcwd(), 'resources', 'simple.html')) as fileinfo:
   print(json.dumps(discovery.test_document(environment_id='{environment_id}', configuration_id='{configuration_id}', file=fileinfo), indent=2))

I also tried to get a list of all the object attributes for discoveryV1 but test_document is not available.

The documentation for this is available at  https://www.ibm.com/watson/developercloud/discovery/api/v1/?python#test-config

**Comment by sanjeevghimire** [comment]
@folajimia This issue is related to the SDK so  Please report this issue to https://github.com/watson-developer-cloud/python-sdk/tree/develop/watson_developer_cloud
