### ISSUE TITLE
 Error: Resource not found, Code: 404

### ISSUE THREAD

**Issue by robettus** [IBM/watson-online-store#154]
I'm following the instructions, but I can't run the app.
In Cloudfoundry I have the next error:
watson_developer_cloud.watson_service.WatsonApiException: Error: Resource not found, Code: 404 , X-dp-watson-tran-id: gateway01-1368408165 , X-global-transaction-id: 7ecac92c5adb5ecd51904065

Help please

Thanks

**Comment by scottdangelo** [comment]
The app appears to be working. Please reopen this if you still have an issue.
