### ISSUE TITLE
WOS 2.0 changes

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-online-store#156]
Add your criteria here:

- [ ] New disco files
- [ ] Add "checkout" to conversation flow
- [ ] Use slots or new assistant features in conversation flow
- [ ] better UI?
- [ ] more robust conversation (don't force remove, don't show empty cart, etc...)
- [ ] multi-user
- [ ] can we do more natural lang instead of numbers like a call tree?
- [ ] might consider serverless action

**Comment by scottdangelo** [comment]
Closing this and tracking in internal repository.
