### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by hendrykeren** [IBM/watson-online-store#160]
Hello sir.
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by stevemar** [comment]
@hendrykeren sure, we don't have anything in mind, feel free to contribute something. was there somewhere you wanted to include it?

**Comment by hendrykeren** [comment]
Of course i will make the best for your project
I will make some improvements to your app

keep listening to xD
respect from me

**Comment by st3ampunk** [comment]
Did the Logo get done?Or shall i contribute?
