### ISSUE TITLE
Add sample dialog to the web app

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-online-store#161]
Creating an issue based on feedback I received over email...

---

> I found your Code about retail chatbot: https://developer.ibm.com/code/patterns/create-cognitive-retail-chatbot/. That's cool but I think the demo (try the app) could be improved a bit. It's not clear what is possible to do or what the shop sells, I think a couple of tweaks in the Dialog would make the demo more effective.

---

This can be solved by simply adding a new `div` before we wrap the `body` tag in this file: https://github.com/IBM/watson-online-store/blob/master/python-flask-server/static/index.html#L62-L63 and add in a sample transcript.

**Comment by scottdangelo** [comment]
Feature requests are now tracked internally.
