### ISSUE TITLE
Importing the workspace JSON doesn't give the whole skill, dialog is missing.

### ISSUE THREAD

**Issue by Adrian-GP** [IBM/watson-online-store#196]
So I cloned the repository and imported the workspace.json to the skill into my assistant, entities and intents are there, but the dialog has the greeting and anything_else nodes only. I tried to re-submit the workspace many times, same results.

**Comment by markstur** [comment]
The dialog only has "Welcome" and "anything_else" -- until you expand the Welcome node.  It is very nested.  There is a screenshot in the README showing it expanded.  It's a little old so I am pushing a new one, but the dialog hasn't changed just the UI around it.
