### ISSUE TITLE
Unable to launch from slack

### ISSUE THREAD

**Issue by ananth777** [IBM/watson-online-store#79]
was a hiccup in trying to reply back to the user.

```
first = user_json['user']['profile']['first_name']
self.create_user_from_ui(user_json)
KeyError: 'first_name'
```

Looks like the the user JSON isn't as expected (it's using "real_name" instead of "first_name")

May be to  add code to the bot to find names in a smarter manner if it make sense

- check "first name"
- check "real_name"
- as a last resort, use "email"

**Comment by stevemar** [comment]
Fixed
