### ISSUE TITLE
Step 4 Configure Watson Discovery. Launch the Watson Conversation tool.  

### ISSUE THREAD

**Issue by LennartFr** [IBM/watson-online-store#81]
4. Configure Watson Discovery

> Launch  the Watson Conversation tool. 
Shouldn't that be "Launch Watson Discovery" ...

**Comment by scottdangelo** [comment]
You are correct. I've a fix up and it'll be merged soon.

**Comment by stevemar** [comment]
739172b3f5ed70f377b2c518eb00ff5c4df234dd fixed the issue
