### ISSUE TITLE
Document using the manifest.yml to upload the Python code to Bluemix if that is supported

### ISSUE THREAD

**Issue by LennartFr** [IBM/watson-online-store#83]
> Under Step 6:  run the application. 
If one does not choose the Deploy to Bluemix button but downloads the code to one's disk with the git command, one can then run the code on one's disk with the python run.py command, which will connect to the three services on Bluemix.

But the code one downloads with the git command also includes a manifest.yml file. Which can be modified and used to upload the Python code to Bluemix to create a watson-online-store, renamed with a unique name. It would be good if the documentation can describe this alternative if it is supported.

**Comment by markstur** [comment]
Thanks for the suggestion, but it looks like we'll stick with the currently documented paths. There are certainly other options as documented by toolchains, etc, but it gets a little ugly here if we try to cover them all.

Since no one has proposed anything, let's close this one.
