### ISSUE TITLE
Clean up Log messages.

### ISSUE THREAD

**Issue by DevOps-GM** [IBM/watson-online-store#86]
Currently there are a log of messages generated for the application when you install it.  Many of the messages are DEBUG messages, but they show up in the log as RED which makes people believe that they are real errors.  The number of default messages makes it hard to find the real error message when you are having problems with the app.

**Comment by scottdangelo** [comment]
The logging level can be changed to reduce the output  [here](https://github.com/IBM/watson-online-store/blob/master/watsononlinestore/watson_online_store.py#L22)
You can change that from logging.DEBUG to logging.WARN or logging.ERROR

**Comment by DevOps-GM** [comment]
@stevemart I understand that I can change the logging level by updating the code.  I would suggest that the code by default be set to logging.WARN or logging.ERROR to avoid having users install and see a large amount of DEBUG messages that will mean nothing to them.  Thanks.
