### ISSUE TITLE
"Deploy to Bluemix" failed

### ISSUE THREAD

**Issue by satoruhamaguchi** [IBM/watson-online-store#91]
I tried to deploy this package by "Deploy to Bluemix" button, but I couldn't succeed.
My delivery pipeline had been failed.

[watson-online-store-20170629094635503-log.txt](https://github.com/IBM/watson-online-store/files/1111713/watson-online-store-20170629094635503-log.txt)

[170629_cflogs_deploy_error.docx](https://github.com/IBM/watson-online-store/files/1111722/170629_cflogs_deploy_error.docx)

I tried to detect problem by these logs, but I couldn't...
Can you deploy these items on your environment ?

**Comment by markstur** [comment]
The logs show that the SLACK_BOT_TOKEN was not set. There are some runtime environment variables that need to be set. See the README for setup instructions. If you think you set it, please double-check. I've had that happen when I don't enter/apply/save/restart quite right and the value is lost.
