### ISSUE TITLE
Document Discovery service storage setup

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-online-store#96]
When setting up discovery, you must now setup storage:
![image](https://user-images.githubusercontent.com/14651388/28283615-72f129e2-6aeb-11e7-9def-d3933812a269.png)

This should be documented.

**Comment by markstur** [comment]
yep, but maybe should mention "if prompted" because this isn't new, but I don't think it is always needed. And this is only in the non- 'Deploy to Bluemix' button part on the setup, right?

**Comment by scottdangelo** [comment]
Yes, it's only for running locally. I'll make it fairly unobtrusive, as
it's a one time deal.

On Jul 17, 2017 3:18 PM, "Mark Sturdevant" <notifications@github.com> wrote:

yep, but maybe should mention "if prompted" because this isn't new, but I
don't think it is always needed. And this is only in the non- 'Deploy to
Bluemix' button part on the setup, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/IBM/watson-online-store/issues/96#issuecomment-315887817>,
or mute the thread
