### ISSUE TITLE
Document adding Conversation credentials to .env for manual setup

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-online-store#97]
There doesn't appear to be any documentation in the README to setup Conversation creds in the .env file.
We need to document this:
# Watson conversation
CONVERSATION_USERNAME=<add_conversation_username>
CONVERSATION_PASSWORD=<add_conversation_password>

**Comment by scottdangelo** [comment]
On further reading, I see some info in "If you decide to run the app locally".
I think this should have a screenshot, at least.

**Comment by markstur** [comment]
there is clip of env.sample just below in Troubleshooting, but "Troubleshooting" is not the best place for it if we want them to get it right the first time.

**Comment by scottdangelo** [comment]
Yeah, I found it eventually. This all just need a bit of refactor.
