### ISSUE TITLE
Deploy to Bluemix doesn't work in UK region

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-online-store#99]
Unconfirmed.
TODO: reproduce

**Comment by sanjeevghimire** [comment]
Services created fine but got a domain error. See below
```
Preparing to start the job...
Logging into Bluemix as user: "sanjeev.ghimire@ibm.com" 
Preparing the build artifacts...
Target: https://api.eu-gb.bluemix.net
Creating service instance wos-conversation-service in org sanjeev.ghimire / space dev as sanjeev.ghimire@ibm.com...
OK
Service wos-conversation-service already exists
Creating service instance wos-cloudantNoSQLDB-service in org sanjeev.ghimire / space dev as sanjeev.ghimire@ibm.com...
OK
Service wos-cloudantNoSQLDB-service already exists
Creating service instance wos-discovery-service in org sanjeev.ghimire / space dev as sanjeev.ghimire@ibm.com...
OK
Service wos-discovery-service already exists
Using manifest file /home/pipeline/c45e8e67-e7ae-4c8b-b0dc-3a38883445b7/manifest.yml

Updating app watson-online-store-20180405151111369 in org sanjeev.ghimire / space dev as sanjeev.ghimire@ibm.com...
OK

FAILED
Domain mybluemix.net not found

Finished: FAILED
```

Created a support ticket: CS0027091

**Comment by markstur** [comment]
This might be due to hardcoded URL like the one addressed for Discovery in #150 

Not enough details to know if this was part of the issue though.

**Comment by markstur** [comment]
Mine fails in London (works in Dallas).  I don't usually use that region so it could be another problem, but looks like some plan of some service is not offered:

API endpoint:   https://api.eu-gb.bluemix.net (API version: 2.106.0)
User:           mark.sturdevant@ibm.com
Org:            mark.sturdevant
Space:          uk_space
Creating service instance wos-conversation-service in org mark.sturdevant / space uk_space as mark.sturdevant@ibm.com...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: No matching deployments for the given plan_id.

**Comment by scottdangelo** [comment]
The first problem is that `manifest.yml` contains `domain: mybluemix.net`. For London, it should have `domain: eu-gb.mybluemix.net`
But there is a further problem that Discovery service is not available in London.
I've a branch `https://github.com/IBM/watson-online-store/tree/londonRegion` that could be used for Deploy to IBM Cloud, except for the Disco problem.
